# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 16:04
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='School',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5b66\u6821\u540d\u79f0')),
                ('logo', models.ImageField(blank=True, null=True, upload_to='school_logo')),
                ('category', models.CharField(choices=[('dx', '\u5927\u5b66'), ('zx', '\u4e2d\u5b66'), ('gz', '\u9ad8\u4e2d'), ('cz', '\u521d\u4e2d'), ('xx', '\u5c0f\u5b66'), ('yey', '\u5e7c\u513f\u56ed')], max_length=3, verbose_name='\u5b66\u6821\u7ea7\u522b')),
                ('tag_leibie', models.CharField(default='211\u9ad8\u6821', max_length=50, verbose_name='\u5b66\u6821\u7c7b\u522b')),
                ('name_en', models.CharField(max_length=100, verbose_name='\u82f1\u6587\u540d\u79f0')),
                ('alias', models.CharField(max_length=100, verbose_name='\u7b80\u79f0')),
                ('provice', models.CharField(max_length=100, verbose_name='\u5730\u533a')),
                ('begintime', models.CharField(max_length=50, verbose_name='\u6210\u7acb\u65f6\u95f4')),
                ('guanwang', models.CharField(max_length=100, verbose_name='\u5b98\u7f51')),
                ('position', models.CharField(max_length=300, verbose_name='\u5730\u5740')),
                ('xiaoxun', models.CharField(max_length=300, verbose_name='\u6821\u8bad')),
                ('yuanxi', models.TextField(max_length=100, verbose_name='\u4e3b\u8981\u9662\u7cfb')),
                ('story', models.TextField(max_length=100, verbose_name='\u5b66\u6821\u5386\u53f2')),
                ('xueshu', models.TextField(max_length=100, verbose_name='\u5b66\u672f\u8d44\u6e90')),
                ('zhuanye', models.TextField(max_length=100, verbose_name='\u5b66\u6821\u4e13\u4e1a')),
                ('zhaosheng', models.TextField(max_length=100, verbose_name='\u62db\u751f\u5c31\u4e1a')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5b66\u6821',
                'verbose_name_plural': '\u5b66\u6821',
            },
        ),
    ]
