# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-14 16:18
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='school',
            name='story',
            field=models.TextField(verbose_name='\u5b66\u6821\u5386\u53f2'),
        ),
        migrations.AlterField(
            model_name='school',
            name='xueshu',
            field=models.TextField(verbose_name='\u5b66\u672f\u8d44\u6e90'),
        ),
        migrations.AlterField(
            model_name='school',
            name='yuanxi',
            field=models.TextField(verbose_name='\u4e3b\u8981\u9662\u7cfb'),
        ),
        migrations.AlterField(
            model_name='school',
            name='zhaosheng',
            field=models.TextField(verbose_name='\u62db\u751f\u5c31\u4e1a'),
        ),
        migrations.AlterField(
            model_name='school',
            name='zhuanye',
            field=models.TextField(verbose_name='\u5b66\u6821\u4e13\u4e1a'),
        ),
    ]
