# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-15 16:07
from __future__ import unicode_literals

from django.db import migrations, models
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('school', '0002_auto_20170815_0018'),
    ]

    operations = [
        migrations.AddField(
            model_name='school',
            name='desc',
            field=models.TextField(default=django.utils.timezone.now, verbose_name='\u5b66\u6821\u7b80\u4ecb'),
            preserve_default=False,
        ),
    ]
