# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 02:46
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yanji', '0002_yanji_status'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Author',
            new_name='Actor',
        ),
    ]
