# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 02:55
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yanji', '0003_auto_20171029_1046'),
    ]

    operations = [
        migrations.CreateModel(
            name='Ptitle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(blank=True, max_length=100, verbose_name='\u6f14\u5458\u804c\u79f0')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6f14\u5458\u804c\u79f0',
                'verbose_name_plural': '\u6f14\u5458\u804c\u79f0',
            },
        ),
        migrations.AddField(
            model_name='actor',
            name='ptitle',
            field=models.ForeignKey(blank=True, default=1, on_delete=django.db.models.deletion.CASCADE, to='yanji.Ptitle'),
            preserve_default=False,
        ),
    ]
