# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 03:31
from __future__ import unicode_literals

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('yanji', '0004_auto_20171029_1055'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='category',
            options={'verbose_name': '\u6f14\u6280\u5206\u7c7b', 'verbose_name_plural': '\u6f14\u6280\u5206\u7c7b'},
        ),
        migrations.AlterField(
            model_name='category',
            name='name',
            field=models.CharField(max_length=100, verbose_name='\u6f14\u6280\u5206\u7c7b'),
        ),
    ]
