# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 03:41
from __future__ import unicode_literals

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('yanji', '0005_auto_20171029_1131'),
    ]

    operations = [
        migrations.RenameField(
            model_name='yanji',
            old_name='actors',
            new_name='actor',
        ),
    ]
