# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 09:00
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    dependencies = [
        ('yanji', '0007_auto_20171029_1220'),
    ]

    operations = [
        migrations.CreateModel(
            name='drama',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5267\u672c')),
                ('content', models.TextField(verbose_name='\u5267\u672c\u5185\u5bb9')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5267\u672c',
                'verbose_name_plural': '\u5267\u672c',
            },
        ),
        migrations.CreateModel(
            name='Movietv',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5f71\u89c6\u5267\u540d\u79f0')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5f71\u89c6\u5267',
                'verbose_name_plural': '\u5f71\u89c6\u5267',
            },
        ),
        migrations.CreateModel(
            name='Movietype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5f71\u89c6\u5267\u7c7b\u578b')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5f71\u89c6\u5267\u7c7b\u578b',
                'verbose_name_plural': '\u5f71\u89c6\u5267\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Scripttype',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u5267\u672c\u7c7b\u578b')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u5267\u672c\u7c7b\u578b',
                'verbose_name_plural': '\u5267\u672c\u7c7b\u578b',
            },
        ),
        migrations.CreateModel(
            name='Taici',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=100, verbose_name='\u53f0\u8bcd')),
                ('content', models.TextField(verbose_name='\u53f0\u8bcd\u5185\u5bb9')),
                ('ctime', models.DateTimeField(default=django.utils.timezone.now, null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('movietv', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yanji.Movietv')),
            ],
            options={
                'verbose_name': '\u53f0\u8bcd',
                'verbose_name_plural': '\u53f0\u8bcd',
            },
        ),
        migrations.AddField(
            model_name='movietv',
            name='movietype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yanji.Movietype'),
        ),
        migrations.AddField(
            model_name='drama',
            name='movietv',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yanji.Movietv'),
        ),
        migrations.AddField(
            model_name='drama',
            name='scripttype',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yanji.Scripttype'),
        ),
        migrations.AddField(
            model_name='drama',
            name='taici',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='yanji.Taici'),
        ),
        migrations.AddField(
            model_name='yanji',
            name='movietv',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='yanji.Movietv'),
            preserve_default=False,
        ),
    ]
