# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-10-29 09:25
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('yanji', '0009_auto_20171029_1719'),
    ]

    operations = [
        migrations.AlterField(
            model_name='drama',
            name='movietv',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='yanji.Movietv'),
        ),
        migrations.AlterField(
            model_name='drama',
            name='taici',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='yanji.Taici'),
        ),
    ]
