# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-16 23:49
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Framework',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u6846\u67b6')),
                ('ctime', models.DateTimeField(null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u6846\u67b6',
                'verbose_name_plural': '\u6846\u67b6',
            },
        ),
        migrations.CreateModel(
            name='Language',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='\u7f16\u7a0b\u8bed\u8a00')),
                ('ctime', models.DateTimeField(null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u7f16\u7a0b\u8bed\u8a00',
                'verbose_name_plural': '\u7f16\u7a0b\u8bed\u8a00',
            },
        ),
        migrations.AddField(
            model_name='framework',
            name='language',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language'),
        ),
    ]
