# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-17 23:18
from __future__ import unicode_literals

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('language', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Tutorial',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=150, verbose_name='\u6559\u7a0b\u540d\u79f0')),
                ('desc', models.TextField(verbose_name='\u7b80\u4ecb')),
                ('ctime', models.DateTimeField(null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('language', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='language.Language')),
            ],
            options={
                'verbose_name': '\u6559\u7a0b\u6307\u5357',
                'verbose_name_plural': '\u6559\u7a0b\u6307\u5357',
            },
        ),
        migrations.CreateModel(
            name='tutorial_item',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=150, verbose_name='\u6559\u7a0b\u7ae0\u8282')),
                ('content', models.TextField(verbose_name='\u7ae0\u8282\u5185\u5bb9')),
                ('ctime', models.DateTimeField(null=True, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('tutorial', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='tutorial.Tutorial')),
            ],
            options={
                'verbose_name': '\u6559\u7a0b\u7ae0\u8282',
                'verbose_name_plural': '\u6559\u7a0b\u7ae0\u8282',
            },
        ),
    ]
