# -*- coding: utf-8 -*-
# Generated by Django 1.10.6 on 2017-08-24 16:15
from __future__ import unicode_literals

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Doctor',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u533b\u751f\u540d\u5b57')),
                ('name_en', models.CharField(max_length=300, verbose_name='\u533b\u751f\u82f1\u6587\u540d')),
                ('face', models.ImageField(upload_to='doctor/face', verbose_name='\u533b\u751f\u5934\u50cf')),
                ('college', models.CharField(max_length=300, verbose_name='\u6bd5\u4e1a\u5927\u5b66')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
            ],
            options={
                'verbose_name': '\u533b\u751f',
                'verbose_name_plural': '\u533b\u751f',
            },
        ),
        migrations.CreateModel(
            name='Hospital',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=300, verbose_name='\u533b\u9662\u540d\u79f0')),
                ('name_en', models.CharField(max_length=300, verbose_name='\u533b\u9662\u540d\u79f0\u82f1\u6587')),
                ('logo', models.ImageField(upload_to='hospital/logo', verbose_name='\u533b\u9662logo')),
                ('desc', models.CharField(max_length=500, verbose_name='\u533b\u9662\u7b80\u4ecb')),
                ('address', models.CharField(max_length=300, verbose_name='\u5730\u70b9')),
                ('project', models.CharField(choices=[('ivf', 'IVF'), ('egg', '\u6350\u5375'), ('sur', '\u4ee3\u5b55'), ('jj', '\u6350\u7cbe'), ('fe', '\u51bb\u5375')], max_length=3, verbose_name='\u9879\u76ee')),
                ('web', models.URLField(default='', max_length=100, verbose_name='\u5b98\u65b9\u7f51\u7ad9')),
                ('ctime', models.DateTimeField(default=datetime.datetime.now, verbose_name='\u6dfb\u52a0\u65f6\u95f4')),
                ('doctors', models.ManyToManyField(to='hospital.Doctor')),
            ],
            options={
                'verbose_name': '\u533b\u9662',
                'verbose_name_plural': '\u533b\u9662',
            },
        ),
    ]
